name: CI

on:
  push:
    branches-ignore: 
      - temp
    tags-ignore: 
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  # Allow cancel job
  actions: write
  # Allow create new deployments
  deployments: write
  # Allow upload package
  packages: write


jobs:
  build:
    name: Build
    uses: ./.github/workflows/sub_version.yaml

  verify:
    name: Verify
    uses: ./.github/workflows/sub_verify.yaml

  publish_beta:
    name: Prerelease
    if: startsWith(github.ref, 'refs/tags/v') == false
    needs:
      - build
      - verify
    uses: ./.github/workflows/sub_publish_prerelease.yaml
    with:
      version: ${{ needs.build.outputs.version }}
      version_primary: ${{ needs.build.outputs.version_primary }}
      version_prerelease: ${{ needs.build.outputs.version_prerelease }}
    secrets: inherit
