name: Sub Publish Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      version_primary:
        required: true
        type: string
      version_prerelease:
        required: false
        type: string
        default: ''
      environment_name:
        required: true
        type: string
        default: ''
  
jobs:
  publish:
    name: Publish Release to PSGallery
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment_name }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        fetch-tags: false

    - name: Update version
      shell: pwsh
      run: |
        $versionParams = @{
          Path = "./src/SitecoreCecSearchModule/SitecoreCecSearchModule.psd1"
          ModuleVersion = "${{ inputs.version_primary }}"
        }
        if("${{ inputs.version_prerelease }}" -ne "") {
          $versionParams.Prerelease = "${{ inputs.version_prerelease }}"
        }

        Write-Host ("Update version to {0}" -f $fullversion)
        Update-ModuleManifest @versionParams

    - name: Publish
      shell: pwsh
      env:
        NUGETKEY: ${{ secrets.NUGET_APIKEY }}
      run: |
        Install-Module Microsoft.PowerShell.PSResourceGet -Repository PSGallery -Force
        Publish-PSResource -path ./src/SitecoreCecSearchModule -Repository PSGallery -APIKey "${env:NUGETKEY}" -Verbose

  verify:
    name: Verify published package
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: false
          fetch-depth: 1
      - name: Install package
        shell: pwsh
        run: |
          ./bld/Install-ReleasedPackage.ps1 -Version ${{ inputs.version }}
