name: Sub Verify

on:
  workflow_call:

jobs:
  verify:
    name: Script Analyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v4
        with:
          path: "~/.local/share/powershell/Modules"
          key: ${{ runner.os }}-PSScriptAnalyzer
      - name: Install from PSGallery
        if: steps.cacher.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Force
          Install-Module -Name Pester -Force -SkipPublisherCheck 
      - name: Run ScriptAnalyzer
        shell: pwsh
        run: Invoke-ScriptAnalyzer -Path src/SitecoreCecSearchModule -IncludeDefaultRules -Recurse -EnableExit -ReportSummary -ExcludeRule PSAvoidTrailingWhitespace
